### ISSUE TITLE
Bad Commad

### ISSUE THREAD

**Issue by cescarcena2021** [aleon2020/ASR_2022-2023#1]
En el readme, el apartado 7.1. En las instruciones para lo del ws el comando colcon es (colcon build --symlink-install), tu lo tiene puesto solo con un - en el symlink.

Un saludo.

**Comment by aleon2020** [comment]
Ya está cambiado, gracias por avisar.

Cualquier problema más avísame 😉

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: cescarcena2021 ***@***.***>
Sent: Saturday, May 20, 2023 12:10:40 PM
To: aleon2020/ASR_2022-2023 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [aleon2020/ASR_2022-2023] Bad Commad (Issue #1)


En el readme, el apartado 7.1. En las instruciones para lo del ws el comando colcon es (colcon build --symlink-install), tu lo tiene puesto solo con un - en el symlink.

Un saludo.

**Comment by aleon2020** [comment]
Todo parece correcto.
